### PR TITLE
Add Spelsberg Smart Pro Wallbox data

### LINKED ISSUE #1: Add Spelsberg Wallbox SmartPro
I own a Spelsberg Wallbox SmartPro with EEBUS support and use it with EEBUS in an experimental EEVC environment. I can add the device to the repository.

### PR DESCRIPTION
**Pull request by mfuchs1984**
Fixed #1

### CODE REVIEW

**Comment by DerAndereAndi** [comment]
Awesome, thank you very much!

Could you check if you have the discovery data also available for the scenario the EV is connected? It is missing a few items.

**Comment by mfuchs1984** [comment]
Updated the files with an EV connected, sorry for the chaotic commit history ;). Let me know if it's good now.

**Comment by DerAndereAndi** [comment]
No worries, thank you very much @mfuchs1984 

I do have one more question though: what car did you connect to the wallbox? And does the wallbox have a setting to enable/disable the PLC connection to the car, and if so on what setting was it?

**Comment by mfuchs1984** [comment]
Connected was a BMW i4 eDrive40

These are the the EEBUS setting
image

These are the PLC settings I suppose
image

**Comment by mfuchs1984** [comment]
Any settings I should play with? I am willing to support.

("Coordinated Charging Mode" "Off" could be the reason for my previously mentined issues with EEVC controlling the Wallbox. I'll give this another try.)

**Comment by DerAndereAndi** [comment]
> ("Coordinated Charging Mode" "Off" could be the reason for my previously mentined issues with EEVC controlling the Wallbox. I'll give this another try.)

That feature is only available if the EV supports and uses ISO15118 communication, which is not the case for your EV. It can not cause any issues with evcc if the EV doesn't support it. evcc does not support coordinated charging.

**Comment by mfuchs1984** [comment]
Thanks much for the information!

**Pull request merged**
